### ISSUE TITLE
The Ellipse is missing on blog page

### ISSUE THREAD

**Issue by Dave-lab12** [Xcceleran-do/Mindplex-landing-page#6]
## Deployed version

![image](https://github.com/Xcceleran-do/Mindplex-landing-page/assets/56738450/774b4e3f-11a0-4130-95a3-d0f08aa6ad63)

## Local version

![image](https://github.com/Xcceleran-do/Mindplex-landing-page/assets/56738450/5722524e-acfe-4a57-a613-c37c6a09c4a8)

**Comment by tensae-b** [comment]
Fixed!
